services:
  pebble-sdk:
    build:
      context: .
      dockerfile: Dockerfile.pebble-sdk
    image: ask-pebble-sdk:4.9.169
    working_dir: /pebble
    volumes:
      - .:/pebble
    command: pebble build
