// Keep this page compact: Android Pebble clients may silently reject long data URLs.
// verify_endpoint_settings.js enforces the final URL budget with representative settings.
// Short DOM ids are intentional; their meaning stays visible in the surrounding markup/code.
module.exports = [
'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
'<title>Ask Pebble Settings</title><style>',
'body{font:14px sans-serif;background:#eee;max-width:400px;margin:auto;padding:12px}.s{background:#fff;padding:12px;margin-bottom:12px}label{display:block;margin-top:8px}input,select,textarea,button{box-sizing:border-box;width:100%;padding:8px;margin-bottom:8px}label input{width:auto}button{font-weight:bold}.save{background:#1976d2;color:#fff}.danger{background:#d32f2f;color:#fff}.muted{background:#777;color:#fff}.status{color:#28752d}.hide{display:none}.link{color:#1769aa;text-decoration:underline}',
'</style></head><body><h1>Ask Pebble Settings</h1><div class="s">',
'<label>API endpoint</label><select id="e" onchange="endpointUI()"><option value="openrouter">OpenRouter</option><option value="openai">OpenAI API</option><option value="custom">Custom OpenAI-compatible API</option></select>',
'<div id="ur" class="hide"><label>Chat Completions URL</label><input id="u" type="url" placeholder="https://.../chat/completions"></div>',
'<label>API key</label><div id="ks" class="status hide">API key saved</div><input id="k" type="text" placeholder="Enter your API key">',
'<p id="p"></p><label>Response language</label><select id="l">',
'<option>Auto</option><option>Japanese</option><option>English</option><option>Chinese (Simplified)</option><option>Chinese (Traditional)</option><option>Korean</option><option>Spanish</option><option>French</option><option>German</option><option>Portuguese</option><option>Italian</option><option>Russian</option><option>Arabic</option><option>Hindi</option></select>',
'<label>System instruction</label><textarea id="i" rows="3" placeholder="Optional custom instruction"></textarea>',
'<label><input id="t" type="checkbox"> Include time context</label><label><input id="g" type="checkbox"> Include location context</label><label><input id="h" type="checkbox"> Include health context</label>',
'<div id="mr"><label>Recommended model</label><select id="m"></select></div><label id="ml">Custom model id</label><input id="cm" placeholder="Optional: override recommended model"><p id="mn"></p>',
'<div id="rl"><button onclick="window.open(\'https://openrouter.ai/settings/keys\',\'_blank\')">Create OpenRouter API key</button><button onclick="window.open(\'https://openrouter.ai/settings/credits\',\'_blank\')">Check credits / usage</button></div>',
'<button class="danger" onclick="deleteKey()">Delete API key</button><button class="muted" onclick="resetMemory()">Reset memory</button></div>',
'<div class="s"><span class="link" onclick="toggleAdvanced()">Advanced settings</span><div id="a" class="hide">',
'<label>Max output tokens</label><select id="x"><option>128</option><option selected>300</option><option>512</option></select>',
'<label>Memory depth</label><select id="d"><option>0</option><option>1</option><option selected>2</option><option>3</option></select>',
'<label>Timeout seconds</label><input id="o" type="number" min="8" max="20" value="12"></div></div>',
'<button class="save" onclick="save()">Save</button><script>',
'var S={},deleted=false,reset=false,$=function(id){return document.getElementById(id)},models={openrouter:[["openai/gpt-5.4-nano","Fastest / lowest cost (GPT-5.4 Nano)"],["openai/gpt-5.4-mini","Standard (GPT-5.4 Mini)"],["openai/gpt-5.6-luna","Quality (GPT-5.6 Luna)"]],openai:[["gpt-5.4-nano","Fastest / lowest cost (GPT-5.4 Nano)"],["gpt-5.4-mini","Standard (GPT-5.4 Mini)"],["gpt-5.6-luna","Quality (GPT-5.6 Luna)"]]};',
'try{S=JSON.parse(decodeURIComponent(location.hash.slice(1)))||{}}catch(e){}',
'function set(id,value){if(value!==undefined&&value!==null)$(id).value=value}',
'if(S.hasApiKey)$("ks").className="status";set("l",S.language);set("i",S.systemInstruction);$("t").checked=S.includeTimeContext!==false;$("g").checked=S.includeLocationContext===true;$("h").checked=S.includeHealthContext===true;set("x",S.maxOutputTokens);set("d",S.memoryDepth);set("o",S.timeoutSeconds);set("e",S.endpointProfile||"openrouter");set("u",S.customBaseUrl||"");set("cm",S.customModelId||"");',
'var initial=$("e").value,initialBase=$("u").value.trim();',
'function defaultModel(p){return p==="openai"?"gpt-5.4-mini":"openai/gpt-5.4-mini"}',
'function fillModels(p){var el=$("m"),current=p===initial?(S.model||defaultModel(p)):defaultModel(p),list=models[p]||[],found=false;el.innerHTML="";for(var i=0;i<list.length;i++){var o=document.createElement("option");o.value=list[i][0];o.text=list[i][1];o.selected=o.value===current;if(o.selected)found=true;el.appendChild(o)}if(!found&&current){o=document.createElement("option");o.value=current;o.text="Current: "+current;o.selected=true;el.appendChild(o)}}',
'function endpointUI(){var p=$("e").value,custom=p==="custom";$("ur").className=custom?"":"hide";$("mr").className=custom?"hide":"";$("rl").className=p==="openrouter"?"":"hide";$("ml").textContent=custom?"Model ID":"Custom model id";$("cm").placeholder=custom?"Required model ID":"Optional: override recommended model";$("mn").textContent=custom?"Required for a custom endpoint.":"Use a model not listed above.";$("p").textContent=p==="openrouter"?"Provider: OpenRouter":p==="openai"?"Provider: OpenAI API":"Provider: Custom API";if(p!==initial){$("ks").className="status hide";$("cm").value=""}if(!custom)fillModels(p)}endpointUI();',
'function toggleAdvanced(){$("a").className=$("a").className?"":"hide"}',
'function deleteKey(){if(confirm("Delete your API key and conversation memory?")){deleted=reset=true;$("k").value="";$("ks").className="status hide"}}function resetMemory(){reset=true;alert("Memory reset")}',
'function save(){var p=$("e").value,base=$("u").value.trim(),customModel=$("cm").value.trim(),changed=p!==initial||(p==="custom"&&base!==initialBase),key=$("k").value.trim();if(p==="custom"&&base.indexOf("https://")!==0)return alert("Enter a complete HTTPS Chat Completions URL.");if(p==="custom"&&!customModel)return alert("Enter a model ID for the custom endpoint.");if(changed&&!key)return alert("Enter an API key for the selected endpoint.");if(changed&&p!=="custom")customModel="";var out={apiKey:key,apiKeyDeleted:deleted&&!key,endpointProfile:p,customBaseUrl:base,language:$("l").value,model:p==="custom"?"":$("m").value,customModelId:customModel,systemInstruction:$("i").value.trim(),includeTimeContext:$("t").checked,includeLocationContext:$("g").checked,includeHealthContext:$("h").checked,maxOutputTokens:$("x").value,memoryDepth:$("d").value,timeoutSeconds:$("o").value,memoryReset:reset};location.href="pebblejs://close#"+encodeURIComponent(JSON.stringify(out))}',
'<\/script></body></html>'
].join('');
